USE SCHEMA AUDIT;

CREATE OR REPLACE TABLE EMPLOYEE_PIPELINE_AUDIT
(
    RUN_ID NUMBER AUTOINCREMENT,
    PIPELINE_NAME VARCHAR(100),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    ROWS_PROCESSED NUMBER,
    ERROR_MESSAGE VARCHAR(500)
);

