CREATE OR REPLACE TABLE SILVER.EMPLOYEE_SILVER
(
    EMP_ID INT,
    EMP_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY NUMBER(10,2),
    HIRE_DATE DATE
);

INSERT INTO SILVER.EMPLOYEE_SILVER
SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    UPPER(DEPARTMENT),
    SALARY,
    HIRE_DATE
FROM BRONZE.EMPLOYEE_RAW;
